// components/ColisUpdateForm.js

import React, { useCallback, useEffect, useMemo } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { getColisByCodeSuivi, updateColisById, fetchOptions } from '../../../../redux/apiCalls/colisApiCalls';
import {
  Form,
  Input,
  InputNumber,
  Select,
  Checkbox,
  Button,
  Spin,
  Alert,
  Row,
  Col,
  DatePicker,
  Tooltip,
  message,
  Typography,
  Tag,
} from 'antd';
import { LoadingOutlined, InfoCircleOutlined, UserOutlined, RetweetOutlined, CopyOutlined, EditOutlined, EnvironmentOutlined } from '@ant-design/icons';
import { useNavigate, useParams } from 'react-router-dom';
import moment from 'moment';
import styles from '../styles/UpdateColis.module.css';

const { Option } = Select;
const { TextArea } = Input;

const UpdateColis = ({ theme }) => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const { selectedColis, loading, error, villes, stores, livreurs, produits, availableColisForReplacement } = useSelector((state) => state.colis);
  const { data: villesData, loading: villesLoading } = villes;
  const { data: storesData, loading: storesLoading } = stores;
  const { data: livreursData, loading: livreursLoading } = livreurs;
  const { data: produitsData, loading: produitsLoading } = produits;
  const { data: availableColisData, loading: availableColisLoading } = { data: availableColisForReplacement, loading: false }; // Adjust as per your state
  const [form] = Form.useForm();
  const { codeSuivi } = useParams();

  const { user } = useSelector(state => state.auth);
  const isAdmin = user.role === 'admin';
  const isLivreur = user.role === 'livreur';
  const isClient = user.role === 'client';

  useEffect(() => {
    dispatch(getColisByCodeSuivi(codeSuivi));
    dispatch(fetchOptions());
  }, [dispatch, codeSuivi]);

  const initialValues = useMemo(() => {
    if (!selectedColis) return {};
    return {
      ...selectedColis,
      ville: (isAdmin || isLivreur) ? selectedColis.ville?._id : undefined,
      store: selectedColis.store?._id,
      livreur: selectedColis.livreur?._id,
      date_programme: selectedColis.date_programme ? moment(selectedColis.date_programme) : null,
      date_livraisant: selectedColis.date_livraisant ? moment(selectedColis.date_livraisant) : null,
      produits: selectedColis.produits && selectedColis.produits.length > 0 
        ? selectedColis.produits.map(p => p.produit) 
        : [],
      tarif_ajouter: isAdmin ? {
        value: selectedColis.tarif_ajouter?.value || 0,
        description: selectedColis.tarif_ajouter?.description || '',
      } : undefined,
      is_remplace: selectedColis.is_remplace || false,
      // Note: replacedColis field removed - code_remplacer is auto-generated
    };
  }, [selectedColis, isAdmin, isLivreur]);

  useEffect(() => {
    if (selectedColis) form.setFieldsValue(initialValues);
  }, [selectedColis, initialValues, form]);

  const onFinish = useCallback((values) => {
    // Note: replacedColis is now optional
    // The code_remplacer will be auto-generated by the backend
    // based on the is_remplace checkbox value

    console.log('=== FRONTEND UPDATE DEBUG ===');
    console.log('Form values:', values);
    console.log('values.is_remplace:', values.is_remplace);
    console.log('selectedColis.is_remplace:', selectedColis.is_remplace);
    console.log('selectedColis.code_remplacer:', selectedColis.code_remplacer);

    // Build update data based on user role
    let updatedData;
    
    if (isLivreur) {
      // Livreur can only update ville
      updatedData = {
        ville: values.ville,
      };
      console.log('Livreur update - Only ville:', updatedData);
    } else {
      // Admin and Client - full update
      updatedData = {
        nom: values.nom,
        tele: values.tele,
        adresse: values.adresse,
        prix: values.prix,
        nature_produit: values.nature_produit,
        commentaire: values.commentaire,
        ouvrir: values.ouvrir === true,
        is_simple: values.is_simple === true,
        is_fragile: values.is_fragile === true,
        is_remplace: values.is_remplace === true, // Explicit boolean
        date_programme: values.date_programme ? values.date_programme.toISOString() : null,
        date_livraisant: values.date_livraisant ? values.date_livraisant.toISOString() : null,
        produits: values.produits || [],
      };

      if (isAdmin) {
        updatedData.tarif_ajouter = {
          value: values.tarif_ajouter?.value || 0,
          description: values.tarif_ajouter?.description || '',
        };
        updatedData.ville = values.ville;
        updatedData.livreur = values.livreur;
      }
    }

    console.log('Updated data being sent:', updatedData);
    console.log('updatedData.is_remplace:', updatedData.is_remplace);

    dispatch(updateColisById(selectedColis._id, updatedData))
      .then(() => {
        console.log('✅ Update completed successfully');
        
        // Show success message based on user role and action
        if (isLivreur) {
          message.success('Ville mise à jour avec succès!');
        } else if (updatedData.is_remplace === true && !selectedColis.code_remplacer) {
          message.success('Colis mis à jour! Le code de remplacement a été généré.');
        } else {
          message.success('Colis mis à jour avec succès!');
        }
        
        // Wait a bit before navigation to ensure state updates
        setTimeout(() => {
          navigate('/dashboard/list-colis');
        }, 1000);
      })
      .catch((error) => {
        console.error('❌ Update failed:', error);
      });
  }, [dispatch, isAdmin, isLivreur, navigate, selectedColis]);

  const loadingIcon = <LoadingOutlined style={{ fontSize: 24 }} spin />;

  return (
    <div className={`${styles.updateFormContainer} ${theme === 'dark' ? 'dark-mode' : ''}`}>
      {loading && <Spin indicator={<LoadingOutlined style={{ fontSize: 24 }} spin />} />}
      {error && <Alert message="Error" description={error} type="error" showIcon style={{ marginBottom: 16 }} />}
      {selectedColis && (
        <Form
          form={form}
          initialValues={initialValues}
          layout="vertical"
          onFinish={onFinish}
        >
          {/* Livreur Restriction Banner */}
          {isLivreur && (
            <Alert
              message={
                <span style={{ fontSize: '16px', fontWeight: 'bold' }}>
                  👤 Accès Livreur - Modification Limitée
                </span>
              }
              description={
                <div style={{ fontSize: '14px' }}>
                  <p style={{ marginBottom: '8px' }}>
                    En tant que <strong>livreur</strong>, vous pouvez uniquement modifier le champ <strong>"Ville"</strong> de ce colis.
                  </p>
                  <p style={{ marginBottom: 0, color: '#3b82f6', fontWeight: 600 }}>
                    ℹ️ Tous les autres champs sont en lecture seule.
                  </p>
                </div>
              }
              type="info"
              showIcon
              icon={<InfoCircleOutlined />}
              style={{ marginBottom: '24px' }}
            />
          )}

          {/* Replacement Status Banner */}
          {selectedColis.is_remplace && selectedColis.code_remplacer && (
            <Alert
              message={
                <span style={{ fontSize: '16px', fontWeight: 'bold' }}>
                  🔒 Colis de Remplacement Actif
                </span>
              }
              description={
                <div style={{ fontSize: '14px' }}>
                  <p style={{ marginBottom: '8px' }}>
                    Ce colis est marqué comme un <strong>colis de remplacement</strong> de manière permanente.
                  </p>
                  <div style={{ 
                    background: theme === 'dark' ? '#78350f' : '#fef3c7',
                    padding: '12px',
                    borderRadius: '6px',
                    border: `2px solid ${theme === 'dark' ? '#f59e0b' : '#fbbf24'}`,
                    marginTop: '8px'
                  }}>
                    <strong>Code de remplacement:</strong>
                    <br />
                    <code style={{ 
                      fontSize: '16px', 
                      fontFamily: 'monospace', 
                      fontWeight: 'bold',
                      color: '#f59e0b'
                    }}>
                      {selectedColis.code_remplacer}
                    </code>
                  </div>
                </div>
              }
              type="warning"
              showIcon
              icon={<RetweetOutlined />}
              style={{ marginBottom: '24px' }}
            />
          )}

          {/* Basic Information */}
          <div className={styles.formSection}>
            <h3 className={styles.sectionTitle}>Basic Information</h3>
            <div className={styles.formGrid}>
              <Form.Item label="Store" name="store">
                <Select disabled>
                  <Option value={selectedColis.store._id}>{selectedColis.store.storeName}</Option>
                </Select>
              </Form.Item>

              <Form.Item label="Code Suivi" name="code_suivi">
                <Input disabled />
              </Form.Item>

              {/* Display code_remplacer if it exists */}
              {selectedColis.code_remplacer && (
                <Form.Item label={
                  <span>
                    <RetweetOutlined style={{ marginRight: 6, color: '#f59e0b' }} />
                    Code Remplacement
                  </span>
                }>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <Typography.Text
                      copyable={{ 
                        text: selectedColis.code_remplacer,
                        icon: [<CopyOutlined key="copy" />, <CopyOutlined key="copied" />]
                      }}
                      style={{
                        fontFamily: 'monospace',
                        fontSize: '14px',
                        fontWeight: 600,
                        color: '#f59e0b',
                        background: theme === 'dark' ? '#78350f' : '#fef3c7',
                        padding: '8px 12px',
                        borderRadius: '6px',
                        border: `1px solid ${theme === 'dark' ? '#f59e0b' : '#fbbf24'}`,
                      }}
                    >
                      {selectedColis.code_remplacer}
                    </Typography.Text>
                    <Tag color="warning" icon={<RetweetOutlined />}>
                      Code de remplacement
                    </Tag>
                  </div>
                </Form.Item>
              )}

              <Form.Item
                label="Nom"
                name="nom"
                rules={[{ required: true, message: 'Please enter the name' }]}
              >
                <Input disabled={isLivreur} />
              </Form.Item>

              <Form.Item
                label="Téléphone"
                name="tele"
                rules={[{ required: true, message: 'Please enter the phone number' }]}
              >
                <Input disabled={isLivreur} />
              </Form.Item>
            </div>
          </div>

          {/* Current Livreur Information - Hidden for Livreur */}
          {!isLivreur && (
            <div className={styles.formSection}>
              <h3 className={styles.sectionTitle}>
                Current Livreur Information
                {isAdmin && (
                  <Tooltip title="You can change the livreur assignment in the Location Details section below">
                    <InfoCircleOutlined style={{ marginLeft: 8, color: '#1890ff', fontSize: '14px' }} />
                  </Tooltip>
                )}
              </h3>
              <div className={styles.formGrid}>
                <Form.Item label="Current Livreur">
                  <Input 
                    disabled 
                    value={selectedColis.livreur ? `${selectedColis.livreur.nom} - ${selectedColis.livreur.tele}` : 'No livreur assigned'}
                    style={{ 
                      color: selectedColis.livreur ? '#52c41a' : '#ff4d4f',
                      fontWeight: selectedColis.livreur ? '500' : 'normal'
                    }}
                  />
                </Form.Item>
                <Form.Item label="Livreur Status">
                  <Input 
                    disabled 
                    value={selectedColis.livreur ? 'Assigned' : 'Not Assigned'}
                    style={{ 
                      color: selectedColis.livreur ? '#52c41a' : '#ff4d4f',
                      fontWeight: '500'
                    }}
                  />
                </Form.Item>
              </div>
            </div>
          )}

          {/* Location Details */}
          <div className={styles.formSection}>
            <h3 className={styles.sectionTitle}>
              Location Details
              {isLivreur && (
                <span style={{ 
                  marginLeft: '12px', 
                  fontSize: '13px', 
                  color: '#10b981', 
                  fontWeight: 600,
                  background: theme === 'dark' ? '#064e3b' : '#d1fae5',
                  padding: '4px 12px',
                  borderRadius: '6px',
                  border: `1px solid ${theme === 'dark' ? '#10b981' : '#6ee7b7'}`
                }}>
                  ✓ Modifiable
                </span>
              )}
            </h3>
            <div className={styles.formGrid}>
              {(isAdmin || isLivreur) && (
                <Form.Item
                label={
                  <span>
                    Ville
                    {isLivreur && <span style={{ color: '#10b981', marginLeft: 6, fontWeight: 700 }}>✓</span>}
                  </span>
                }
                name="ville"
                rules={[{ required: true, message: 'Please select a city' }]}
              >
                <Select
                  showSearch
                  placeholder="Select a city"
                  loading={villesLoading}
                  optionFilterProp="children"
                  filterOption={(input, option) =>
                    option.children.toLowerCase().includes(input.toLowerCase())
                  }
                  style={isLivreur ? {
                    border: '2px solid #10b981',
                    borderRadius: '6px'
                  } : {}}
                >
                  {villesData?.map(ville => (
                    <Option key={ville._id} value={ville._id}>
                      {ville.nom}
                    </Option>
                  ))}
                </Select>
              </Form.Item>
              )}
              {isAdmin && (
                <Form.Item
                  label={
                    <Tooltip title="Assign or change the livreur responsible for this colis">
                      <span>
                        <UserOutlined style={{ marginRight: 8 }} />
                        Livreur
                      </span>
                    </Tooltip>
                  }
                  name="livreur"
                  rules={[{ required: false, message: 'Please select a livreur' }]}
                >
                  <Select
                    showSearch
                    placeholder="Select a livreur (optional)"
                    allowClear
                    loading={livreursLoading}
                    optionFilterProp="children"
                    filterOption={(input, option) =>
                      option.children.toLowerCase().includes(input.toLowerCase())
                    }
                  >
                    {livreursData?.map(livreur => (
                      <Option key={livreur._id} value={livreur._id}>
                        {livreur.nom} - {livreur.tele}
                      </Option>
                    ))}
                  </Select>
                </Form.Item>
              )}
              <Form.Item
                label="Adresse"
                name="adresse"
                rules={[{ required: true, message: 'Please enter the address' }]}
              >
                <Input disabled={isLivreur} />
              </Form.Item>
            </div>
          </div>

          {/* Product Details */}
          <div className={styles.formSection}>
            <h3 className={styles.sectionTitle}>Product Details</h3>
            <div className={styles.formGrid}>
              <Form.Item
                label="Nature Produit"
                name="nature_produit"
                rules={[{ required: true }]}
              >
                <Input disabled={isLivreur} />
              </Form.Item>

              <Form.Item
                label="Prix"
                name="prix"
                rules={[{ required: true }]}
              >
                <InputNumber
                  disabled={isLivreur}
                  style={{ width: '100%' }}
                  formatter={value => `${value} DH`}
                  parser={value => value.replace(/DH\s?|(,*)/g, '')}
                />
              </Form.Item>
            </div>

            <div className={styles.checkboxGroup}>
              <Form.Item name="ouvrir" valuePropName="checked">
                <Checkbox disabled={isLivreur}>Ouvrir</Checkbox>
              </Form.Item>
              <Form.Item name="is_simple" valuePropName="checked">
                <Checkbox disabled={isLivreur}>Simple</Checkbox>
              </Form.Item>
              <Form.Item name="is_fragile" valuePropName="checked">
                <Checkbox disabled={isLivreur}>Fragile</Checkbox>
              </Form.Item>
              <Form.Item name="is_remplace" valuePropName="checked">
                <Tooltip 
                  title={
                    isLivreur 
                      ? "Les livreurs ne peuvent pas modifier ce champ." 
                      : selectedColis.is_remplace === true 
                        ? "Le statut 'Remplacer' est permanent et ne peut pas être désactivé une fois activé." 
                        : "Cochez pour marquer ce colis comme un remplacement. Cette action est irréversible."
                  }
                  placement="top"
                >
                  <Checkbox disabled={isLivreur || selectedColis.is_remplace === true}>
                    <span style={{ 
                      display: 'flex', 
                      alignItems: 'center', 
                      gap: '6px',
                      padding: '4px 8px',
                      borderRadius: '6px',
                      background: (isLivreur || selectedColis.is_remplace === true)
                        ? (theme === 'dark' ? '#4b5563' : '#e5e7eb')
                        : (theme === 'dark' ? '#78350f' : '#fef3c7'),
                      border: `1px solid ${(isLivreur || selectedColis.is_remplace === true)
                        ? (theme === 'dark' ? '#6b7280' : '#d1d5db')
                        : (theme === 'dark' ? '#f59e0b' : '#fbbf24')}`,
                      fontWeight: 600,
                      cursor: (isLivreur || selectedColis.is_remplace === true) ? 'not-allowed' : 'pointer'
                    }}>
                      <RetweetOutlined style={{ color: (isLivreur || selectedColis.is_remplace === true) ? '#9ca3af' : '#f59e0b' }} />
                      Remplacer {selectedColis.is_remplace === true && '🔒'}
                    </span>
                  </Checkbox>
                </Tooltip>
              </Form.Item>
            </div>
            
            {/* Dynamic info based on is_remplace value - Hidden for Livreur */}
            {!isLivreur && (
              <Form.Item noStyle shouldUpdate={(prevValues, currentValues) => prevValues.is_remplace !== currentValues.is_remplace}>
                {({ getFieldValue }) => {
                  const isRemplace = getFieldValue('is_remplace');
                  const currentCodeRemplacer = selectedColis.code_remplacer;
                  
                  if (isRemplace && !currentCodeRemplacer) {
                  // Checkbox is checked but no code_remplacer exists yet
                  return (
                    <Alert
                      message="Code de Remplacement sera généré automatiquement"
                      description={
                        <div>
                          <p style={{ marginBottom: '8px' }}>
                            <strong>✅ Action:</strong> Lors de la sauvegarde, un code de remplacement sera automatiquement créé.
                          </p>
                          <p style={{ marginBottom: '8px' }}>
                            <strong>Format:</strong> <code style={{ background: '#fef3c7', padding: '2px 6px', borderRadius: '4px', fontFamily: 'monospace' }}>{selectedColis.code_suivi}-Change</code>
                          </p>
                          <p style={{ marginBottom: 0, color: '#d97706', fontWeight: 600 }}>
                            ⚠️ Note: Cette action est <strong>irréversible</strong>. Une fois activé, le statut "Remplacer" ne peut plus être désactivé.
                          </p>
                        </div>
                      }
                      type="success"
                      showIcon
                      style={{ marginTop: '16px', marginBottom: '16px' }}
                    />
                  );
                } else if (isRemplace && currentCodeRemplacer) {
                  // Checkbox is checked and code already exists (disabled state)
                  return (
                    <Alert
                      message="Code de Remplacement actif (Permanent)"
                      description={
                        <div>
                          <p style={{ marginBottom: '8px' }}>
                            <strong>ℹ️ Info:</strong> Ce colis est marqué comme remplacement.
                          </p>
                          <p style={{ marginBottom: 0 }}>
                            <strong>Code de remplacement:</strong> <code style={{ background: '#fef3c7', padding: '2px 6px', borderRadius: '4px', fontFamily: 'monospace' }}>{currentCodeRemplacer}</code>
                          </p>
                        </div>
                      }
                      type="info"
                      showIcon
                      style={{ marginTop: '16px', marginBottom: '16px' }}
                    />
                  );
                }
                  return null;
                }}
              </Form.Item>
            )}
          </div>

      

          {/* Submit Button */}
          <Form.Item style={{ textAlign: 'right' }}>
            <Button
              type="primary"
              htmlType="submit"
              loading={loading}
              icon={isLivreur ? <EnvironmentOutlined /> : <EditOutlined />}
              style={isLivreur ? {
                background: '#10b981',
                borderColor: '#10b981'
              } : {}}
            >
              {isLivreur ? 'Mettre à jour la Ville' : isAdmin ? 'Mettre à jour le Colis' : 'Update Colis'}
            </Button>
          </Form.Item>
        </Form>
      )}
    </div>
  );
};

export default UpdateColis;
